<template>
  <div class="wrapper">
    <ul class="content">
      <li>BscrollDemo1</li>
      <li>BscrollDemo2</li>
      <li>BscrollDemo3</li>
      <li>BscrollDemo4</li>
      <li>BscrollDemo5</li>
      <li>BscrollDemo6</li>
      <li>BscrollDemo7</li>
      <li>BscrollDemo8</li>
      <li>BscrollDemo9</li>
      <li>BscrollDemo10</li>
      <li>BscrollDemo11</li>
      <li>BscrollDemo12</li>
      <li>BscrollDemo13</li>
      <li>BscrollDemo14</li>
      <li>BscrollDemo15</li>
      <li>BscrollDemo16</li>
      <li>BscrollDemo17</li>
      <li>BscrollDemo18</li>
      <li>BscrollDemo19</li>
      <li>BscrollDemo20</li>
      <li>BscrollDemo21</li>
      <li>BscrollDemo22</li>
      <li>BscrollDemo23</li>
      <li>BscrollDemo24</li>
      <li>BscrollDemo25</li>
      <li>BscrollDemo26</li>
      <li>BscrollDemo27</li>
      <li>BscrollDemo28</li>
      <li>BscrollDemo29</li>
      <li>BscrollDemo30</li>
      <li>BscrollDemo31</li>
      <li>BscrollDemo32</li>
      <li>BscrollDemo33</li>
      <li>BscrollDemo34</li>
      <li>BscrollDemo35</li>
      <li>BscrollDemo36</li>
      <li>BscrollDemo37</li>
      <li>BscrollDemo38</li>
      <li>BscrollDemo39</li>
      <li>BscrollDemo40</li>
      <li>BscrollDemo41</li>
      <li>BscrollDemo42</li>
      <li>BscrollDemo43</li>
      <li>BscrollDemo44</li>
      <li>BscrollDemo45</li>
      <li>BscrollDemo46</li>
      <li>BscrollDemo47</li>
      <li>BscrollDemo48</li>
      <li>BscrollDemo49</li>
      <li>BscrollDemo50</li>
      <li>BscrollDemo51</li>
      <li>BscrollDemo52</li>
      <li>BscrollDemo53</li>
      <li>BscrollDemo54</li>
      <li>BscrollDemo55</li>
      <li>BscrollDemo56</li>
      <li>BscrollDemo57</li>
      <li>BscrollDemo58</li>
      <li>BscrollDemo59</li>
      <li>BscrollDemo60</li>
      <li>BscrollDemo61</li>
      <li>BscrollDemo62</li>
      <li>BscrollDemo63</li>
      <li>BscrollDemo64</li>
      <li>BscrollDemo65</li>
      <li>BscrollDemo66</li>
      <li>BscrollDemo67</li>
      <li>BscrollDemo68</li>
      <li>BscrollDemo69</li>
      <li>BscrollDemo70</li>
      <li>BscrollDemo71</li>
      <li>BscrollDemo72</li>
      <li>BscrollDemo73</li>
      <li>BscrollDemo74</li>
      <li>BscrollDemo75</li>
      <li>BscrollDemo76</li>
      <li>BscrollDemo77</li>
      <li>BscrollDemo78</li>
      <li>BscrollDemo79</li>
      <li>BscrollDemo80</li>
      <li>BscrollDemo81</li>
      <li>BscrollDemo82</li>
      <li>BscrollDemo83</li>
      <li>BscrollDemo84</li>
      <li>BscrollDemo85</li>
      <li>BscrollDemo86</li>
      <li>BscrollDemo87</li>
      <li>BscrollDemo88</li>
      <li>BscrollDemo89</li>
      <li>BscrollDemo90</li>
      <li>BscrollDemo91</li>
      <li>BscrollDemo92</li>
      <li>BscrollDemo93</li>
      <li>BscrollDemo94</li>
      <li>BscrollDemo95</li>
      <li>BscrollDemo96</li>
      <li>BscrollDemo97</li>
      <li>BscrollDemo98</li>
      <li>BscrollDemo99</li>
      <li>BscrollDemo100</li>
      <li>BscrollDemo1</li>
      <li>BscrollDemo2</li>
      <li>BscrollDemo3</li>
      <li>BscrollDemo4</li>
      <li>BscrollDemo5</li>
      <li>BscrollDemo6</li>
      <li>BscrollDemo7</li>
      <li>BscrollDemo8</li>
      <li>BscrollDemo9</li>
      <li>BscrollDemo10</li>
      <li>BscrollDemo11</li>
      <li>BscrollDemo12</li>
      <li>BscrollDemo13</li>
      <li>BscrollDemo14</li>
      <li>BscrollDemo15</li>
      <li>BscrollDemo16</li>
      <li>BscrollDemo17</li>
      <li>BscrollDemo18</li>
      <li>BscrollDemo19</li>
      <li>BscrollDemo20</li>
      <li>BscrollDemo21</li>
      <li>BscrollDemo22</li>
      <li>BscrollDemo23</li>
      <li>BscrollDemo24</li>
      <li>BscrollDemo25</li>
      <li>BscrollDemo26</li>
      <li>BscrollDemo27</li>
      <li>BscrollDemo28</li>
      <li>BscrollDemo29</li>
      <li>BscrollDemo30</li>
      <li>BscrollDemo31</li>
      <li>BscrollDemo32</li>
      <li>BscrollDemo33</li>
      <li>BscrollDemo34</li>
      <li>BscrollDemo35</li>
      <li>BscrollDemo36</li>
      <li>BscrollDemo37</li>
      <li>BscrollDemo38</li>
      <li>BscrollDemo39</li>
      <li>BscrollDemo40</li>
      <li>BscrollDemo41</li>
      <li>BscrollDemo42</li>
      <li>BscrollDemo43</li>
      <li>BscrollDemo44</li>
      <li>BscrollDemo45</li>
      <li>BscrollDemo46</li>
      <li>BscrollDemo47</li>
      <li>BscrollDemo48</li>
      <li>BscrollDemo49</li>
      <li>BscrollDemo50</li>
      <li>BscrollDemo51</li>
      <li>BscrollDemo52</li>
      <li>BscrollDemo53</li>
      <li>BscrollDemo54</li>
      <li>BscrollDemo55</li>
      <li>BscrollDemo56</li>
      <li>BscrollDemo57</li>
      <li>BscrollDemo58</li>
      <li>BscrollDemo59</li>
      <li>BscrollDemo60</li>
      <li>BscrollDemo61</li>
      <li>BscrollDemo62</li>
      <li>BscrollDemo63</li>
      <li>BscrollDemo64</li>
      <li>BscrollDemo65</li>
      <li>BscrollDemo66</li>
      <li>BscrollDemo67</li>
      <li>BscrollDemo68</li>
      <li>BscrollDemo69</li>
      <li>BscrollDemo70</li>
      <li>BscrollDemo71</li>
      <li>BscrollDemo72</li>
      <li>BscrollDemo73</li>
      <li>BscrollDemo74</li>
      <li>BscrollDemo75</li>
      <li>BscrollDemo76</li>
      <li>BscrollDemo77</li>
      <li>BscrollDemo78</li>
      <li>BscrollDemo79</li>
      <li>BscrollDemo80</li>
      <li>BscrollDemo81</li>
      <li>BscrollDemo82</li>
      <li>BscrollDemo83</li>
      <li>BscrollDemo84</li>
      <li>BscrollDemo85</li>
      <li>BscrollDemo86</li>
      <li>BscrollDemo87</li>
      <li>BscrollDemo88</li>
      <li>BscrollDemo89</li>
      <li>BscrollDemo90</li>
      <li>BscrollDemo91</li>
      <li>BscrollDemo92</li>
      <li>BscrollDemo93</li>
      <li>BscrollDemo94</li>
      <li>BscrollDemo95</li>
      <li>BscrollDemo96</li>
      <li>BscrollDemo97</li>
      <li>BscrollDemo98</li>
      <li>BscrollDemo99</li>
      <li>BscrollDemo100</li>
      <li>BscrollDemo1</li>
      <li>BscrollDemo2</li>
      <li>BscrollDemo3</li>
      <li>BscrollDemo4</li>
      <li>BscrollDemo5</li>
      <li>BscrollDemo6</li>
      <li>BscrollDemo7</li>
      <li>BscrollDemo8</li>
      <li>BscrollDemo9</li>
      <li>BscrollDemo10</li>
      <li>BscrollDemo11</li>
      <li>BscrollDemo12</li>
      <li>BscrollDemo13</li>
      <li>BscrollDemo14</li>
      <li>BscrollDemo15</li>
      <li>BscrollDemo16</li>
      <li>BscrollDemo17</li>
      <li>BscrollDemo18</li>
      <li>BscrollDemo19</li>
      <li>BscrollDemo20</li>
      <li>BscrollDemo21</li>
      <li>BscrollDemo22</li>
      <li>BscrollDemo23</li>
      <li>BscrollDemo24</li>
      <li>BscrollDemo25</li>
      <li>BscrollDemo26</li>
      <li>BscrollDemo27</li>
      <li>BscrollDemo28</li>
      <li>BscrollDemo29</li>
      <li>BscrollDemo30</li>
      <li>BscrollDemo31</li>
      <li>BscrollDemo32</li>
      <li>BscrollDemo33</li>
      <li>BscrollDemo34</li>
      <li>BscrollDemo35</li>
      <li>BscrollDemo36</li>
      <li>BscrollDemo37</li>
      <li>BscrollDemo38</li>
      <li>BscrollDemo39</li>
      <li>BscrollDemo40</li>
      <li>BscrollDemo41</li>
      <li>BscrollDemo42</li>
      <li>BscrollDemo43</li>
      <li>BscrollDemo44</li>
      <li>BscrollDemo45</li>
      <li>BscrollDemo46</li>
      <li>BscrollDemo47</li>
      <li>BscrollDemo48</li>
      <li>BscrollDemo49</li>
      <li>BscrollDemo50</li>
      <li>BscrollDemo51</li>
      <li>BscrollDemo52</li>
      <li>BscrollDemo53</li>
      <li>BscrollDemo54</li>
      <li>BscrollDemo55</li>
      <li>BscrollDemo56</li>
      <li>BscrollDemo57</li>
      <li>BscrollDemo58</li>
      <li>BscrollDemo59</li>
      <li>BscrollDemo60</li>
      <li>BscrollDemo61</li>
      <li>BscrollDemo62</li>
      <li>BscrollDemo63</li>
      <li>BscrollDemo64</li>
      <li>BscrollDemo65</li>
      <li>BscrollDemo66</li>
      <li>BscrollDemo67</li>
      <li>BscrollDemo68</li>
      <li>BscrollDemo69</li>
      <li>BscrollDemo70</li>
      <li>BscrollDemo71</li>
      <li>BscrollDemo72</li>
      <li>BscrollDemo73</li>
      <li>BscrollDemo74</li>
      <li>BscrollDemo75</li>
      <li>BscrollDemo76</li>
      <li>BscrollDemo77</li>
      <li>BscrollDemo78</li>
      <li>BscrollDemo79</li>
      <li>BscrollDemo80</li>
      <li>BscrollDemo81</li>
      <li>BscrollDemo82</li>
      <li>BscrollDemo83</li>
      <li>BscrollDemo84</li>
      <li>BscrollDemo85</li>
      <li>BscrollDemo86</li>
      <li>BscrollDemo87</li>
      <li>BscrollDemo88</li>
      <li>BscrollDemo89</li>
      <li>BscrollDemo90</li>
      <li>BscrollDemo91</li>
      <li>BscrollDemo92</li>
      <li>BscrollDemo93</li>
      <li>BscrollDemo94</li>
      <li>BscrollDemo95</li>
      <li>BscrollDemo96</li>
      <li>BscrollDemo97</li>
      <li>BscrollDemo98</li>
      <li>BscrollDemo99</li>
      <li>BscrollDemo100</li>
    </ul>
  </div>
</template>
<script>


import Bscroll from 'better-scroll'

export default {
  name: "demo", data() {
    return {
      scroll: null
    }
  },
  created() {
    // this.scroll = new Bscroll(document.querySelector('.wrapper'),{})
  },
  mounted() {
    this.scroll = new Bscroll(document.querySelector('.wrapper'),{})
  }
}
</script>

<style scoped>
.wrapper {
  height: 150px;
  background-color: red;
}
</style>
